server:
  port: 8000

spring:
  output:
    ansi:
      enabled: ALWAYS

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  datasource:
    url: ${POSTGRES_HOST:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:root}

  jpa:
    open-in-view: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    show-sql: true

  liquibase:
    change-log: classpath:db-migrations/changelog.xml
    enabled: true
    drop-first: false